config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moviechooser.chooser.urls')),
    path('library/', include('moviechooser.library.urls')),
    path('mylist/', include('moviechooser.lists.urls')),
    path('user/', include('moviechooser.accounts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviechooser/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
]

moviechooser/chooser/urls.py
from django.urls import path
from . import views

app_name = 'chooser'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('results/', views.results, name='results'),
]

moviechooser/library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    # path('movie/<str:pk>/', views.movie_detail, name='detail'),
    path('surprise/', views.surprise, name='surprise'),
    path('search/', views.search_results, name='search_results')
]

moviechooser/lists/urls.py
from django.urls import path
from . import views

app_name = 'lists'
urlpatterns = [
    path('', views.my_list, name='my_list'),
    path('remove/<int:pk>/', views.remove_item, name='remove'),
    path('update/<int:pk>/', views.update_item, name='update'),
]

moviechooser/chooser/models.py
# from django.db import models

# from moviechooser.library.models import Genre, Movie

# class MovieChoice(models.Model):
#     GENRE_SELECT = [(genre.id, genre.name) for genre in Genre.objects.all()]

#     genre = models.CharField(max_length=20, choices=GENRE_SELECT)
#     sorted_runtimes = [movie.runtime for movie in Movie.objects.order_by('runtime')]
#     min_runtime = sorted_runtimes[0]
#     max_runtime = sorted_runtimes[-1]

moviechooser/library/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(unique=True, max_length=50)

    def __str__(self):
        return self.name
        

class Actor(models.Model):
    name = models.CharField(unique=True, max_length=200)

    def __str__(self):
        return self.name


class Director(models.Model):
    name = models.CharField(unique=True, max_length=200)

    def __str__(self):
        return self.name


class Movie(models.Model):
    imdbid = models.CharField(primary_key=True, max_length=20)
    title = models.CharField(max_length=200)
    rated = models.CharField(max_length=20, blank=True, null=True)
    released = models.DateField()
    runtime = models.IntegerField(null=True)
    genre = models.ManyToManyField(Genre)
    director = models.ManyToManyField(Director)
    writer = models.CharField(max_length=500)
    actors = models.ManyToManyField(Actor)
    plot = models.CharField(max_length=500, null=True)
    language = models.CharField(max_length=40, null=True)
    country = models.CharField(max_length=40, null=True)
    poster_url = models.CharField(max_length=200)
    imdb_rating = models.IntegerField(null=True)
    metacritic = models.IntegerField(null=True)
    rotten_tomatoes = models.IntegerField(null=True)
    avg_rating = models.IntegerField(null=True)
    type_field = models.CharField(db_column='type_', max_length=12, null=True)

    def __str__(self):
        return self.title

    def get_genre(self):
        genre_str = ', '.join([genre.name for genre in self.genre.all()])
        return genre_str

    def get_actors(self):
        actors_str = ', '.join([actors.name for actors in self.actors.all()])
        return actors_str

    def get_director(self):
        director_str = ', '.join([director.name for director in self.director.all()])
        return director_str

    def get_decade(self):
        decade = self.get_year()
        decade = decade[:3] + '0s'
        return decade

    def get_year(self):
        year = self.released.strftime("%Y")
        return year
        

class OnDemand(models.Model):
    imdbid = models.ForeignKey(
        Movie, on_delete=models.CASCADE
    )
    service = models.CharField(max_length=50)
    url = models.CharField(max_length=300)
    added = models.DateField()
    updated = models.DateField()

    def __str__(self):
        return self.imdbid + "--" + self.service

moviechooser/lists/models.py
from django.db import models
from django.contrib.auth.models import User

from moviechooser.library.models import Movie

# Create your models here.
class Item(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    imdbid = models.CharField(max_length=20)
    movie = models.ForeignKey(Movie, on_delete=models.SET_NULL, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    watched = models.BooleanField(default=False)

    # def __str__(self):
    #     return self.title

    class Meta:
        ordering = ['watched', '-date_added']

moviechooser/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

moviechooser/chooser/forms.py
# from django import forms

# from moviechooser.library.models import Genre
# from .models import MovieChoice

# class MovieChoiceForm(forms.ModelForm):

#     class Meta:
#         model = MovieChoice
#         fields = '__all__'
        # widgets = {
        #     'genre': forms.CheckboxSelectMultiple(),
        #     'runtime': forms.IntegerField()
        # }

moviechooser/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import CreateUserForm
from .decorators import unauthenticated_user

# Create your views here.

@unauthenticated_user
def register_page(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account created for ' + user)
            return redirect('accounts:login')

    context = {'form': form}
    return render(request, 'register.html', context)

@unauthenticated_user
def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('chooser:homepage'))
        else:
            messages.info(request, 'Username or password is incorrect')
    context = {}
    return render(request, 'login.html', context)

def logout_page(request):
    logout(request)
    return redirect('accounts:login')

moviechooser/chooser/views.py
from random import randint

from django.shortcuts import get_object_or_404, render
from django.db.models import Max, Min, Q
from django.core.paginator import Paginator

from moviechooser.library.models import Movie, Genre
from moviechooser.lists.models import Item


def homepage(request):
    genres = Genre.objects.all()
    max_runtime = list(Movie.objects.aggregate(Max('runtime')).values())[0]
    min_runtime = list(Movie.objects.aggregate(Min('runtime')).values())[0]
    decades = sorted(set([movie.get_decade() for movie in Movie.objects.all()]), reverse=True)

    context = {
        'genres': genres,
        'min_runtime': min_runtime,
        'max_runtime': max_runtime,
        'decades': decades,
    }
    return render(request, 'homepage.html', context)


def results(request):
    get_copy = request.GET.copy()
    parameters = get_copy.pop('page', True) and get_copy.urlencode()

    genre_selection = request.GET.getlist('genre_choice')
    runtime = request.GET.getlist('runtime')[0]
    decade_selection = request.GET.getlist('decade_choice')

    if genre_selection != []:
        movies = Movie.objects.filter(genre__name__in=genre_selection)
    else:
        movies = Movie.objects.all()

    movies = (movies
                .filter(
                    Q(runtime__lte=runtime),
                    Q(*[('released__startswith', decade[:3]) for decade in decade_selection],
                    _connector=Q.OR)
                )
                .distinct()
                .order_by('-avg_rating')
            )

    if request.user is not None:
        try:
            items = Item.objects.filter(user=request.user)
            item_imdbid = set()
            for item in items:
                item_imdbid.add(item.imdbid)

            for movie in movies:
                if movie.imdbid in item_imdbid:
                    movie.added = True
                    item = Item.objects.filter(user=request.user, imdbid=movie.imdbid)
                    movie.item_id = str(item[0].id)
                else:
                    movie.added = False
        except:
            pass
            
    paginator = Paginator(movies, 30)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'parameters': parameters,
        'page_obj': page_obj,
    }

    return render(request, 'results.html', context=context)

moviechooser/library/views.py
from random import randint, shuffle

from django.core.cache import cache
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
from django.db.models import Q

from moviechooser.lists.models import Item
from moviechooser.library.models import Movie


def index(request):
    get_copy = request.GET.copy()
    parameters = get_copy.pop('page', True) and get_copy.urlencode()
    
    movies = cache.get('movie_selection')
    if not movies:
        movies = Movie.objects.order_by('?')
        cache.set('movie_selection', movies)

    try:
        items = Item.objects.filter(user=request.user)
        item_imdbid = set()
        for item in items:
            item_imdbid.add(item.imdbid)

        for movie in movies:
            if movie.imdbid in item_imdbid:
                item = Item.objects.filter(user=request.user, imdbid=movie.imdbid)
                movie.item_id = str(item[0].id)
                movie.added = True
            else:
                movie.added = False
    except:
        pass

    paginator = Paginator(movies, 30)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'library.html', context=context)


def surprise(request):
    if 'movie' in request.get_full_path():
        random_movie = Movie.objects.get(imdbid=request.GET.getlist('movie')[0])
    else:
        movies = Movie.objects.all()
        if len(movies) > 1:
            rand_index = randint(0, len(movies) - 1)
        else: 
            rand_index = 0
        random_movie = movies[rand_index]

    try:
        item = Item.objects.filter(user=request.user, imdbid=random_movie.imdbid)
        random_movie.item_id = str(item[0].id)
        random_movie.added = True
    except:
        random_movie.added = False

    context = {
        'movie': random_movie,
        'try_again': True,
    }

    return render(request, 'surprise.html', context=context)


# def movie_detail(request, pk):
#     movie = get_object_or_404(Movie, imdbid=pk)
#     referer = request.META.get('HTTP_REFERER')
#     if 'library' in referer and 'movie' not in referer:
#         from_library = True
#         from_list = False
#         cache.set('from_library', from_library)
#         cache.set('from_list', from_list)
#     elif 'mylist' in referer:
#         from_library = False
#         from_list = True
#         cache.set('from_library', from_library)
#         cache.set('from_list', from_list)
#     else:
#         from_library = cache.get('from_library')
#         from_list = cache.get('from_list')

#     try:
#         item = Item.objects.filter(user=request.user, imdbid=movie.imdbid)
#         movie.item_id = str(item[0].id)
#         movie.added = True
#     except:
#         movie.added = False

#     print('from_list', from_list)
#     print('from_library', from_library)

#     context = {
#         'movie': movie,
#         'actors': movie.get_actors(),
#         'director': movie.get_director(),
#         'year': movie.get_year(),
#         'genre': movie.get_genre(),
#         'from_library': from_library,
#         'from_list': from_list
#     }
#     return render(request, 'detail_page.html', context=context)


def search_results(request):
    get_copy = request.GET.copy()
    parameters = get_copy.pop('page', True) and get_copy.urlencode()

    query = request.GET.get('q')
    movies = Movie.objects.filter(
        Q(title__icontains=query)
        ).order_by('-avg_rating')

    try:
        items = Item.objects.filter(user=request.user)
        item_imdbid = set()
        for item in items:
            item_imdbid.add(item.imdbid)

        for movie in movies:
            if movie.imdbid in item_imdbid:
                movie.added = True
                item = Item.objects.filter(user=request.user, imdbid=movie.imdbid)
                movie.item_id = str(item[0].id)
            else:
                movie.added = False
    except:
        pass

    paginator = Paginator(movies, 30)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'parameters': parameters,
        'page_obj': page_obj,
    }

    return render(request, 'search_results.html', context=context)
        

moviechooser/lists/views.py
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect

from moviechooser.library.models import Movie
from moviechooser.lists.models import Item

@login_required(login_url='accounts:login')
def my_list(request):
    if request.method == 'POST':
        item_imdbid = request.POST['imdbid']
        # Check user's saved items
        if not Item.objects.filter(user=request.user, imdbid=item_imdbid).exists():
            movie = Movie.objects.get(imdbid=item_imdbid)
            item = Item.objects.create(user=request.user, imdbid=item_imdbid, movie=movie)
            if 'surprise' and '?' in request.META.get('HTTP_REFERER'):
                return redirect(request.META.get('HTTP_REFERER'))
            # if 'surprise' and not '?' in request.META.get('HTTP_REFERER'):
            #     return redirect(request.META.get('HTTP_REFERER') + f"?movie={item_imdbid}")
        return redirect(request.META.get('HTTP_REFERER') + f"#{item_imdbid}")
    else:
        list_items = Item.objects.filter(user=request.user)
        for item in list_items:
            movie = Movie.objects.get(imdbid=item.movie.imdbid)
        context = {
            'list_items': list_items
        }
    return render(request, 'my_list.html', context)

@login_required(login_url='accounts:login')
def remove_item(request, pk):
    item = Item.objects.get(id=pk)
    item.delete()
    if request.META.get('HTTP_REFERER') == reverse('lists:my_list'):
        return redirect(request.META.get('HTTP_REFERER'))
    else:
        if 'surprise' and '?' in request.META.get('HTTP_REFERER'):
            return redirect(request.META.get('HTTP_REFERER'))
        return redirect(request.META.get('HTTP_REFERER') + f"#{item.imdbid}")

@login_required(login_url='accounts:login')
def update_item(request, pk):
    item = Item.objects.get(id=pk)
    if item.watched:
        item.watched = False
    else:
        item.watched = True
    item.save()

    return redirect(reverse('lists:my_list'))

moviechooser/templates/detail_page.html
{% extends 'base.html' %} {% block content %}

<div class="jumbotron">
  <h1 class="display-4 text-center">Movie Details</h1>
  <p class="lead text-center">What you need to know...</p>
</div>

<div class="page-container">{% include 'movie_detail.html' %}</div>

{% endblock %}

moviechooser/templates/homepage.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<div class="jumbotron">
    <h1 class="display-4 text-center"><strong>Welcome to Movie Chooser</strong></h1>
    <p class="lead text-center">Stop deciding, start watching!</p>
</div>


<div class="page-container">

    <div class="choices-panel">
        <h2>Choose genre(s)</h2>
        <p class="sub-heading">Leave blank to select all</p>
        <br>
        
        <form action="{% url 'chooser:results' %}" method="get">

            <div class="choice-buttons">
                {% for genre in genres %}
                    <input type="checkbox" name="genre_choice" id="{{ genre.id }}" value="{{ genre.name }}">
                    <label for="{{ genre.id }}">{{ genre.name }}</label><br>
                {% endfor %}
            </div> 
    </div>

    <div class="choices-panel">
        <h2>Choose movie length</h2>
        <br>
        <div class="range-slider">
            <label for="runtime">Runtime up to:</label>
            <div class="keep-row">
                <input class="range-slider__range" type="range" id="runtime" name="runtime" 
                    value="{{ max_runtime }}" min="{{ min_runtime }}" max="{{ max_runtime }}">
                    <span class="range-slider__value">0</span>
                    <p>mins</p>
            </div> 
        </div>
    </div>


    <div class="choices-panel">
        <h2>Choose decade(s)</h2>
        <p class="sub-heading">Leave blank to select all</p>
        <div class="choice-buttons">
            {% for decade in decades %}
                <input type="checkbox" name="decade_choice" id="{{ decade }}" value="{{ decade }}">
                <label for="{{ decade }}">{{ decade }}</label><br>
            {% endfor %}
        </div>
        <br>
    </div>

    <div class="choices-panel">
        <input class="btn btn-primary btn-lg" type="submit" value="GO!">
    </div>

        </form>

    </div>

</div>

{% endblock %}

moviechooser/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<h1>Can't decide what to watch?</h1>
<h2 class="center-subhead">Recently Added</h2><br>

{% for movie in movies %}
<div class="card-container">
    <div class="card mb-3" style="width: 36rem;">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img class="card-img" src="{{ movie.poster_url }}" alt="{{ movie.title }} poster image">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                <h5 class="card-title">{{ movie.title }}</h5>
                <p class="card-text">{{ movie.plot }}</p>
                <a href="#" class="btn btn-primary">Add to list</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

moviechooser/templates/library.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<div class="jumbotron">
    <h1 class="display-4 center-subhead">All Movies</h1>
</div>

<div class="page-container">

    {% for movie in page_obj %}

        {% include 'movie_card.html' %}

    {% endfor %}
    
</div>

{% include 'pagination.html' %}

{% endblock %}

moviechooser/templates/movie_card.html
{% load static %}

<div class="centered-element" id="{{ movie.imdbid }}">
  <div class="card mb-3" style="width: 36rem">
    <div class="row no-gutters">
      <div class="col-4">
        <img
          class="card-img"
          src="{{ movie.poster_url }}"
          alt="{{ movie.title }} poster image"
        />
      </div>

      <div class="col-8">
        <div class="card-body">
          <h5 class="card-title">{{ movie.title }}</h5>
          <p class="card-text">{{ movie.plot }}</p>
          <p class="card-text score">Average Score: {{ movie.avg_rating }}</p>

          {% if not movie.added %}
          <form action="{% url 'lists:my_list' %}" method="post">
            {% csrf_token %}
            <button
              type="submit"
              class="btn btn-primary list-btn"
              name="imdbid"
              value="{{movie.imdbid}}"
            >
              <i class="fas fa-plus"></i>
              <p class="button-text">List</p>
            </button>
          </form>
          {% else %}
          <form action="{% url 'lists:remove' movie.item_id %}" method="post">
            {% csrf_token %}
            <button
              class="btn btn-primary added"
              name="imdbid"
              value="{{
              movie.imdbid
              }}"
            >
              <i class="fas fa-minus" alt="Added to list"></i>
              <p class="button-text">Added</p>
            </button>
          </form>
          {% endif %}

          <button
            class="btn btn-primary toggle-detail"
            name="more"
            data-id="{{movie.imdbid}}"
          >
            <i class="fas fa-info-circle" alt="Movie info"></i>
            <p class="button-text">More</p>
          </button>
        </div>
      </div>
      <div class="card-detail card-text hide" id="{{movie.imdbid}}-detail">
        <ul>
          <li>
            Starring: 
                {{ movie.actors.all|join:", " }}
          </li>
          <li>
            Directed by: 
                {{ movie.director.all|join:", " }}
          </li>
          <li>Released: {{ movie.released|date:"Y" }}</li>
          <li>Genre: 
                {{ movie.genre.all|join:", " }}
          </li>
        </ul>
        <ul class="ratings-details">
          {% if movie.imdb_rating >= 0 %}
          <li>
            <img
              class="ratings-logo"
              src="{% static 'images/imdb.png' %}"
              alt="IMDB rating"
            />
            {{ movie.imdb_rating }}
          </li>
          {% endif %} {% if movie.rotten_tomatoes >= 0 %}
          <li>
            <img
              class="ratings-logo"
              src="{% static 'images/rotten.png' %}"
              alt="IMDB rating"
            />
            {{ movie.rotten_tomatoes }}
          </li>
          {% endif %} {% if movie.metacritic >= 0 %}
          <li>
            <img
              class="ratings-logo"
              src="{% static 'images/metacritic.png' %}"
              alt="IMDB rating"
            />
            {{ movie.metacritic }}
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</div>

moviechooser/templates/my_list.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div class="jumbotron">
  <h1 class="display-4 center-subhead">My List</h1>
</div>

<div class="page-container">
  {% if list_items %}

  <table id="my_list_table">
    {% for list_item in list_items %}

    <div class="centered-element">
      <div class="card mb-3" style="width: 36rem">
        <div class="row no-gutters">
          <div class="col-4">
            <img
              class="card-img"
              src="{{ list_item.movie.poster_url }}"
              alt="{{ movie.title }} poster image"
            />
          </div>

          <div class="col-8">
            <div class="card-body">
              <h5 class="card-title">{{ list_item.movie.title }}</h5>
              <p class="card-text">{{ list_item.movie.plot }}</p>
              <p class="card-text score">
                Average Score: {{ list_item.movie.avg_rating }}
              </p>
              <p class="card-text">Added on: {{ list_item.date_added }}</p>

              <form
                action="{% url 'lists:remove' list_item.id %}"
                method="post"
              >
                {% csrf_token %}
                <button
                  type="submit"
                  class="btn btn-primary remove"
                  name="remove"
                  value="{{"
                  list_item.id
                  }}
                >
                  <i class="fas fa-minus" alt="Remove from list"></i>
                  <p class="button-text">Remove</p>
                </button>
              </form>

              <form
                action="{% url 'lists:update' list_item.id %}"
                method="post"
              >
                {% csrf_token %} {% if not list_item.watched %}
                <button
                  type="submit"
                  class="btn btn-primary watched"
                  name="update"
                  value="{{"
                  list_item.id
                  }}
                >
                  <i class="far fa-square" alt="Updated watched movie"></i>
                  <p class="button-text">watched</p>
                </button>
                {% else %}
                <button
                  type="submit"
                  class="btn btn-primary watched"
                  name="update"
                  value="{{list_item.id}}"
                >
                  <i
                    class="far fa-check-square"
                    alt="Updated watched movie"
                  ></i>
                  <p class="button-text">watched</p>
                </button>
                {% endif %}
              </form>

              <button
                class="btn btn-primary toggle-detail"
                name="more"
                data-id="{{list_item.movie.imdbid}}"
              >
                <i class="fas fa-info-circle" alt="Movie info"></i>
                <p class="button-text">More</p>
              </button>
            </div>
          </div>
          <div
            class="card-detail card-text hide"
            id="{{list_item.movie.imdbid}}-detail"
          >
        <ul>
          <li>
            Starring: 
                {{ list_item.movie.actors.all|join:", " }}
          </li>
          <li>
            Directed by: 
                {{ list_item.movie.director.all|join:", " }}
          </li>
          <li>Released: {{ list_item.movie.released|date:"Y" }}</li>
          <li>Genre: 
                {{ list_item.movie.genre.all|join:", " }}
          </li>
        </ul>
            <ul class="ratings-details">
              {% if list_item.movie.imdb_rating >= 0 %}
              <li>
                <img
                  class="ratings-logo"
                  src="{% static 'images/imdb.png' %}"
                  alt="IMDB rating"
                />
                {{ list_item.movie.imdb_rating }}
              </li>
              {% endif %} {% if list_item.movie.rotten_tomatoes >= 0 %}
              <li>
                <img
                  class="ratings-logo"
                  src="{% static 'images/rotten.png' %}"
                  alt="IMDB rating"
                />
                {{ list_item.movie.rotten_tomatoes }}
              </li>
              {% endif %} {% if list_item.movie.metacritic >= 0 %}
              <li>
                <img
                  class="ratings-logo"
                  src="{% static 'images/metacritic.png' %}"
                  alt="IMDB rating"
                />
                {{ list_item.movie.metacritic }}
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
  </table>
</div>
{% else %}

<div class="choices-panel">
  <h2 class="center-subhead"><strong>No movies added to list</strong></h2>

  {% endif %}
</div>

{% endblock %}

moviechooser/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/"><img alt="Movie Chooser" src="{% static 'images/moviechooser_transparent_100.png' %}"
        height="40"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" 
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
    {% with request.resolver_match.url_name as url_name %}
      <ul class="navbar-nav">
        <li class="nav-item {% if url_name == 'index'%}active{% endif %}">
          <a class="nav-link" href="{% url 'index' %}">Library <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if url_name == 'my_list'%}active{% endif %}"">
          <a class="nav-link" href="{% url 'lists:my_list' %}">My List</a>
        </li>
        <li class="nav-item {% if url_name == 'surprise'%}active{% endif %}">
          <a class="nav-link" href="{% url 'surprise' %}">Surprise Me</a>
        </li>
      </ul>
    {% endwith %}

      <div class="nav-right">
        <form class="form-inline my-2 my-lg-0 search-box" action="{% url 'search_results' %}" method="get">
          <input class="form-control mr-sm-2" type="text" 
            name="q" placeholder="Search titles" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Go</button>
        </form>

        <div class="nav-item nav-link auth-info">
          <ul class="navbar-nav auth-list">
          {% if user.is_authenticated %}
          <li class="nav-item auth-item">Hello, {{ request.user }}</li>
          <li class="nav-item auth-item logout-link"><a href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item auth-item register-link"><a href="{% url 'accounts:register' %}">Register</a></li>
          <p class="nav-item auth-item auth-slash">/</p>
          <li class="nav-item auth-item login-link"><a href="{% url 'accounts:login' %}">Login</a></li>
          {% endif %}
          </ul>
        </div>
      </div>

    </div>
</nav>